version: '3.4'

services:
  rentlyapi:
    image: rentlyapi
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - data:/data/db

volumes:
  data: {}
